title: Halaman Github Pertama Saya
author: nuralibasyah gans
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ini coba coba ganti deskripsi buat page github... gatau sih sebenernya mau diisi apa
  cuma ya diisi panjang aja supaya ga pendek banget gitu.. segini masih kurang panjang
  yaudah tambahin dikit nah pas.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
